import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class PetsService {

  constructor() { }
  names: Array<string> = [
    'Mia Wallace Burrington',
    'Tyber',
    'Starfox',
    'Big B',
    'Bulma',
    'Gracie Mae',
    'Zha Zha',
    'Makani',
    'Hallie',
    'Zoli',
    ' Willey',
    'Brownie',
    'Kermit',
    'Gronk',
    'Iggy Pup',
    'Mitzy',
    'Meela',
    'Hommie',
    'Mary Margeret',
    'Vidalia',
    'Taswold Tasewell',
    'Jackie Pink',
    'Huckleberry Finn',
    'Egon',
    'Olympia',
    'Ford',
    'Didgit',
    'Howl',
    'Brandy IV',
    'Lilian Rose',
    'Alicia',
    'Deuce',
    'Scout Montes',
    'Reina',
    'Noodge',
    'Beta',
    'Scout Friedland',
    'Bron King Trojan Boisfontaine',
    'Fatso',
    'Pomp',
    'graham walter',
    'Jake Lobster',
    'Chaucer',
    'Judo',
    'Divot',
    'Billy Bigelow',
    'Aute',
    'Fizz',
    'Jimmy',
    'Prince Callie',
    'Khan',
    'Rod',
    'Hannah Belle',
    'Sammie',
    'Dini',
    'Wilhelmina',
    'Wolfgang',
    'Chika-Latte',
    'Nora Belle',
    'Chevelle',
    'Madras',
    'Katja',
    'Kenna',
    'Newton',
    'Regis',
    'Satski',
    'Matlock',
    'Po Jaggy',
    'Tomato',
    'Jette',
    'Red Baron',
    'Mambo',
    'Cino',
    'Kona Bean Schendel',
    'Annie Bulis',
    'Sigmund',
    'Katana',
    'Ichiha',
    'Kashi Lu Sivesind',
    'Rubin',
    'Fredrick',
    'Mulder',
    'Ezekiel',
    'Leia Subramanian',
    'Kipper',
    'Norman Kish',
    'The Stig',
    'Beefy',
    'Indiana Jones Snapper',
    'Sluggo',
    'Bogie',
    'Mouogli',
    'Rebel Dawg',
    'Tanaa',
    'Ruby Petals',
    'Prinz',
    'Alejandro',
    'Pompeii',
    'Miss Scarlett',
    'Speed King',
  ]
  getRandomPetName() {
    return this.names[Math.floor(Math.random() * this.names.length)]
  }
}
